### ISSUE TITLE
[Feature Request] changeValue support for shorthand properties

### ISSUE THREAD

**Issue by caseymhunt** [kunukn/postcss-alter-property-value#1]
Currently changeValue appears to only support changing the entire value to another. 

I would like to be able to change one component of a value, for example, a complex CSS shorthand. 

For example, I would like to be able to change:
`border: 1px solid black` to `border: 1px solid #000000`

**Comment by kunukn** [comment]
Sounds interesting. I will look into it.

**Comment by kunukn** [comment]
I have updated to support partial value replacement.
Example configuration.

```
'border': {
  task: 'changeValue',
  to: '#000',
  whenRegex: {
    mode: 'partial',
    value: 'black', 
    flags: 'i'
  }
}
```
