### ISSUE TITLE
[Feature Request] Wildcard property selector

### ISSUE THREAD

**Issue by caseymhunt** [kunukn/postcss-alter-property-value#2]
This may be way out of scope for this, however it would be useful to be able to crawl for _any_ property to change it's value. 

Desired example:
```js
* : {
    task: 'changeValue',
    to: '#f00',
    whenValueEquals: 'red'
},
```

In this case it would change any instance of `red` to `#f00` for any property.

**Comment by kunukn** [comment]
I think it is in scope. 
I have update the code to include this.

The `*` character is likely never to be used as a real property name in the future, so I kept the name `*` to be used in the configuration.
